version: '3.8'

services:
  php:
    build: ./
    volumes:
      - ../php:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d
